/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EntryPoint {
  export type CreateJobParamsStruct = {
    jobId: string;
    creator: AddressLike;
    maxTokenAmount: BigNumberish;
    deadline: BigNumberish;
    createdAt: BigNumberish;
    priority: BigNumberish;
    quality: BigNumberish;
    minReputation: BigNumberish;
  };

  export type CreateJobParamsStructOutput = [
    jobId: string,
    creator: string,
    maxTokenAmount: bigint,
    deadline: bigint,
    createdAt: bigint,
    priority: bigint,
    quality: bigint,
    minReputation: bigint
  ] & {
    jobId: string;
    creator: string;
    maxTokenAmount: bigint;
    deadline: bigint;
    createdAt: bigint;
    priority: bigint;
    quality: bigint;
    minReputation: bigint;
  };

  export type BidStruct = {
    bidId: string;
    jobId: string;
    bidder: AddressLike;
    createdAt: BigNumberish;
    tokenAmount: BigNumberish;
    timeToComplete: BigNumberish;
    reputationScore: BigNumberish;
    status: BigNumberish;
    exists: boolean;
  };

  export type BidStructOutput = [
    bidId: string,
    jobId: string,
    bidder: string,
    createdAt: bigint,
    tokenAmount: bigint,
    timeToComplete: bigint,
    reputationScore: bigint,
    status: bigint,
    exists: boolean
  ] & {
    bidId: string;
    jobId: string;
    bidder: string;
    createdAt: bigint;
    tokenAmount: bigint;
    timeToComplete: bigint;
    reputationScore: bigint;
    status: bigint;
    exists: boolean;
  };
}

export interface EntryPointInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "INITIAL_REPUTATION"
      | "MAX_BID"
      | "MAX_REPUTATION"
      | "REP_PENALTY"
      | "REP_REWARD"
      | "coordinator"
      | "createJob"
      | "deployer"
      | "escrow"
      | "finalizeJob"
      | "getBidCountForJob"
      | "getBidDetails"
      | "getBidsForJob"
      | "getEscrowDetails"
      | "getJobAssignee"
      | "getJobDetails"
      | "getJobsByNode"
      | "getNodeReputation"
      | "isJobExpired"
      | "isMaxBidReached"
      | "jobBidIndexPlusOne"
      | "jobBids"
      | "jobToAssignee"
      | "jobs"
      | "markJobAsCompleted"
      | "markJobAsFailed"
      | "nodeToJobs"
      | "placeBid"
      | "refundEscrow"
      | "releaseEscrowFunds"
      | "reputation"
      | "token"
      | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BidPlaced"
      | "EscrowCreated"
      | "EscrowRefund"
      | "EscrowReleased"
      | "JobAssigned"
      | "JobCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "INITIAL_REPUTATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_BID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_REPUTATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REP_PENALTY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REP_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "coordinator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [EntryPoint.CreateJobParamsStruct]
  ): string;
  encodeFunctionData(functionFragment: "deployer", values?: undefined): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(functionFragment: "finalizeJob", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getBidCountForJob",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidDetails",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidsForJob",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrowDetails",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobAssignee",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobDetails",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobsByNode",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isJobExpired",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isMaxBidReached",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "jobBidIndexPlusOne",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "jobBids",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "jobToAssignee",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "markJobAsCompleted",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "markJobAsFailed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "nodeToJobs",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "placeBid",
    values: [string, BigNumberish, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refundEscrow",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseEscrowFunds",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "reputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "INITIAL_REPUTATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_BID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_REPUTATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REP_PENALTY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "REP_REWARD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "coordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deployer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBidCountForJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBidDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBidsForJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEscrowDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getJobAssignee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getJobDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getJobsByNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isJobExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMaxBidReached",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "jobBidIndexPlusOne",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobBids", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "jobToAssignee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markJobAsCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markJobAsFailed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nodeToJobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseEscrowFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reputation", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace BidPlacedEvent {
  export type InputTuple = [
    bidId: string,
    jobId: string,
    bidder: AddressLike,
    tokenAmount: BigNumberish
  ];
  export type OutputTuple = [
    bidId: string,
    jobId: string,
    bidder: string,
    tokenAmount: bigint
  ];
  export interface OutputObject {
    bidId: string;
    jobId: string;
    bidder: string;
    tokenAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    jobId: string,
    bidId: string,
    payer: AddressLike,
    payee: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    bidId: string,
    payer: string,
    payee: string,
    amount: bigint
  ];
  export interface OutputObject {
    jobId: string;
    bidId: string;
    payer: string;
    payee: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundEvent {
  export type InputTuple = [jobId: string];
  export type OutputTuple = [jobId: string];
  export interface OutputObject {
    jobId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [jobId: string, amount: BigNumberish];
  export type OutputTuple = [jobId: string, amount: bigint];
  export interface OutputObject {
    jobId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobAssignedEvent {
  export type InputTuple = [jobId: string, node: AddressLike];
  export type OutputTuple = [jobId: string, node: string];
  export interface OutputObject {
    jobId: string;
    node: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    jobId: string,
    creator: AddressLike,
    maxTokenAmount: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    creator: string,
    maxTokenAmount: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    jobId: string;
    creator: string;
    maxTokenAmount: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EntryPoint extends BaseContract {
  connect(runner?: ContractRunner | null): EntryPoint;
  waitForDeployment(): Promise<this>;

  interface: EntryPointInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  INITIAL_REPUTATION: TypedContractMethod<[], [bigint], "view">;

  MAX_BID: TypedContractMethod<[], [bigint], "view">;

  MAX_REPUTATION: TypedContractMethod<[], [bigint], "view">;

  REP_PENALTY: TypedContractMethod<[], [bigint], "view">;

  REP_REWARD: TypedContractMethod<[], [bigint], "view">;

  coordinator: TypedContractMethod<[], [string], "view">;

  createJob: TypedContractMethod<
    [_params: EntryPoint.CreateJobParamsStruct],
    [void],
    "nonpayable"
  >;

  deployer: TypedContractMethod<[], [string], "view">;

  escrow: TypedContractMethod<[], [string], "view">;

  finalizeJob: TypedContractMethod<[_jobId: string], [void], "nonpayable">;

  getBidCountForJob: TypedContractMethod<[_jobId: string], [bigint], "view">;

  getBidDetails: TypedContractMethod<
    [_jobId: string, _bidId: string],
    [[string, string, string, bigint, bigint, bigint, bigint, bigint]],
    "view"
  >;

  getBidsForJob: TypedContractMethod<
    [_jobId: string],
    [EntryPoint.BidStructOutput[]],
    "view"
  >;

  getEscrowDetails: TypedContractMethod<
    [_jobId: string],
    [[string, string, string, string, bigint, boolean]],
    "view"
  >;

  getJobAssignee: TypedContractMethod<[_jobId: string], [string], "view">;

  getJobDetails: TypedContractMethod<
    [_jobId: string],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        EntryPoint.BidStructOutput,
        bigint,
        bigint
      ]
    ],
    "view"
  >;

  getJobsByNode: TypedContractMethod<[node: AddressLike], [string[]], "view">;

  getNodeReputation: TypedContractMethod<[node: AddressLike], [bigint], "view">;

  isJobExpired: TypedContractMethod<[_jobId: string], [boolean], "view">;

  isMaxBidReached: TypedContractMethod<[_jobId: string], [boolean], "view">;

  jobBidIndexPlusOne: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [bigint],
    "view"
  >;

  jobBids: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        bidId: string;
        jobId: string;
        bidder: string;
        createdAt: bigint;
        tokenAmount: bigint;
        timeToComplete: bigint;
        reputationScore: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  jobToAssignee: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  jobs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        EntryPoint.BidStructOutput,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        jobId: string;
        creator: string;
        createdAt: bigint;
        deadline: bigint;
        maxTokenAmount: bigint;
        priority: bigint;
        quality: bigint;
        minReputation: bigint;
        bestBid: EntryPoint.BidStructOutput;
        bestBidScore: bigint;
        bidCount: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  markJobAsCompleted: TypedContractMethod<
    [_jobId: string],
    [void],
    "nonpayable"
  >;

  markJobAsFailed: TypedContractMethod<[_jobId: string], [void], "nonpayable">;

  nodeToJobs: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  placeBid: TypedContractMethod<
    [
      _bidId: string,
      _tokenAmount: BigNumberish,
      _jobId: string,
      _createdAt: BigNumberish,
      _timeToComplete: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  refundEscrow: TypedContractMethod<[_jobId: string], [void], "nonpayable">;

  releaseEscrowFunds: TypedContractMethod<
    [_jobId: string],
    [void],
    "nonpayable"
  >;

  reputation: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  token: TypedContractMethod<[], [string], "view">;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "INITIAL_REPUTATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_BID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_REPUTATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REP_PENALTY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REP_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "coordinator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<
    [_params: EntryPoint.CreateJobParamsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalizeJob"
  ): TypedContractMethod<[_jobId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBidCountForJob"
  ): TypedContractMethod<[_jobId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBidDetails"
  ): TypedContractMethod<
    [_jobId: string, _bidId: string],
    [[string, string, string, bigint, bigint, bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBidsForJob"
  ): TypedContractMethod<
    [_jobId: string],
    [EntryPoint.BidStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEscrowDetails"
  ): TypedContractMethod<
    [_jobId: string],
    [[string, string, string, string, bigint, boolean]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJobAssignee"
  ): TypedContractMethod<[_jobId: string], [string], "view">;
  getFunction(
    nameOrSignature: "getJobDetails"
  ): TypedContractMethod<
    [_jobId: string],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        EntryPoint.BidStructOutput,
        bigint,
        bigint
      ]
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJobsByNode"
  ): TypedContractMethod<[node: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getNodeReputation"
  ): TypedContractMethod<[node: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isJobExpired"
  ): TypedContractMethod<[_jobId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "isMaxBidReached"
  ): TypedContractMethod<[_jobId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "jobBidIndexPlusOne"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "jobBids"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        bidId: string;
        jobId: string;
        bidder: string;
        createdAt: bigint;
        tokenAmount: bigint;
        timeToComplete: bigint;
        reputationScore: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobToAssignee"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        EntryPoint.BidStructOutput,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        jobId: string;
        creator: string;
        createdAt: bigint;
        deadline: bigint;
        maxTokenAmount: bigint;
        priority: bigint;
        quality: bigint;
        minReputation: bigint;
        bestBid: EntryPoint.BidStructOutput;
        bestBidScore: bigint;
        bidCount: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markJobAsCompleted"
  ): TypedContractMethod<[_jobId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "markJobAsFailed"
  ): TypedContractMethod<[_jobId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nodeToJobs"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "placeBid"
  ): TypedContractMethod<
    [
      _bidId: string,
      _tokenAmount: BigNumberish,
      _jobId: string,
      _createdAt: BigNumberish,
      _timeToComplete: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "refundEscrow"
  ): TypedContractMethod<[_jobId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseEscrowFunds"
  ): TypedContractMethod<[_jobId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputation"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BidPlaced"
  ): TypedContractEvent<
    BidPlacedEvent.InputTuple,
    BidPlacedEvent.OutputTuple,
    BidPlacedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefund"
  ): TypedContractEvent<
    EscrowRefundEvent.InputTuple,
    EscrowRefundEvent.OutputTuple,
    EscrowRefundEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;
  getEvent(
    key: "JobAssigned"
  ): TypedContractEvent<
    JobAssignedEvent.InputTuple,
    JobAssignedEvent.OutputTuple,
    JobAssignedEvent.OutputObject
  >;
  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;

  filters: {
    "BidPlaced(string,string,address,uint256)": TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;
    BidPlaced: TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;

    "EscrowCreated(string,string,address,address,uint256)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "EscrowRefund(string)": TypedContractEvent<
      EscrowRefundEvent.InputTuple,
      EscrowRefundEvent.OutputTuple,
      EscrowRefundEvent.OutputObject
    >;
    EscrowRefund: TypedContractEvent<
      EscrowRefundEvent.InputTuple,
      EscrowRefundEvent.OutputTuple,
      EscrowRefundEvent.OutputObject
    >;

    "EscrowReleased(string,uint256)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;

    "JobAssigned(string,address)": TypedContractEvent<
      JobAssignedEvent.InputTuple,
      JobAssignedEvent.OutputTuple,
      JobAssignedEvent.OutputObject
    >;
    JobAssigned: TypedContractEvent<
      JobAssignedEvent.InputTuple,
      JobAssignedEvent.OutputTuple,
      JobAssignedEvent.OutputObject
    >;

    "JobCreated(string,address,uint256,uint256)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
  };
}
